### ISSUE TITLE
trackedConnection.IsAlive is not returning false for sometime when client turnsoff the internet/or unplugs network cable

### ISSUE THREAD

**Issue by UshaV-Questionmark** [SignalR/SignalR#3476]
@DamianEdwards 

We wrote a server side  PresenceMonitor to check whether a client is online or offline inspired by your PresenceMonitor implementation on GitHub.

https://github.com/DamianEdwards/NDCLondon2013/blob/master/UserPresence/PresenceMonitor.cs

However we are seeing the issue described in the following link which is closed now. 

https://github.com/SignalR/SignalR/issues/2081 

With WebSockets transport, if the network is disconnected by turning off internet on client side then the connection is marked dead after 17 minutes. The trackedConnection.IsAlive property is not returning false until this timeframe is expired and then OnDisconnected is getting fired. Whereas with LongPolling transport the connection is recognized as dead with in one minute.

We are using Singnalr 2.2 and as per your comments on the above issue we believe that this issue is fixed in this version. Are we missing something here?

Thanks,
Usha

**Comment by Joe-U-Questionmark** [comment]
Is anyone monitoring this issue queue? This issue is holding us up and I thought someone would have responded after 21 days.

**Comment by halter73** [comment]
@UshaV-Questionmark @Joe-U-Questionmark Sorry for the delayed response. Unfortunately, I am unable to reproduce this issue.

I tried reproing this by running our [raw connection sample app](https://github.com/SignalR/SignalR/tree/3a219c101587333d562f04f30903d50ad9773e1c/samples/Microsoft.AspNet.SignalR.Samples/Raw) on IIS. I then connected with multiple clients using WebSockets, and unplugged the network cable from one of the clients. I then observed the connection events from the still-connected clients.

I see the following output in messages (I did this about 3 times and consistently saw the same results):

* "7/27/2015 12:52:46 PM: f154941d-daf0-459e-b082-2eeb1911f0e7 joined from [IP Address]"
* "7/27/2015 12:53:33 PM: f154941d-daf0-459e-b082-2eeb1911f0e7 disconnected uncleanly"

This is the expected behavior. It should take a little over 40 seconds by default for an unclean disconnect to fire. The main reason it takes this long is to give the client a smallish window where it can reconnect.

The fact that you don't see `IsAlive` return false until 17 minutes after the web socket disconnects implies that the [IWebSocket.OnClose callback](https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/Transports/WebSocketTransport.cs#L101) is firing 17 minutes too late. Can you determine which [`IWebSocket` implementation](https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/Owin/OwinWebSocketHandler.cs#L66) is being used? `OwinWebSocket` or `WebSocketContext`? Are you running SignalR on IIS?

Also, are you able to repro this issue on a LAN? I'm wondering if some sort of proxy might be causing issues.

Maybe we could try setting `IsAlive` to false when the last write fails like we do for [other transports](https://github.com/SignalR/SignalR/blob/3a219c101587333d562f04f30903d50ad9773e1c/src/Microsoft.AspNet.SignalR.Core/Transports/TransportDisconnectBase.cs#L146). A failed write should always occur if the client disconnects since SignalR sends a keep alive every 10 seconds by default. Is there any reason we aren't doing this @davidfowl?

**Comment by UshaV-Questionmark** [comment]
@halter73 We are hosting our SiganlR application on IIS (version 8). I am not sure which IWebsocket implementation is used by SiganlR under the hood, is there a way to determine this if it helps? We could reproduce the issue on LAN. The client is not connected to server via a proxy in this scenario. 
The following are the log messages written by our PresenceMonitor on Server during our testing. 

Date:2015-07-28 14:18:10,938 
Message:OnConnected called for ID:2|200000 
 
Date:2015-07-28 14:19:15,438 
Message:Connection is alive ID:460f9930-263f-4bbd-ab0b-aad28bce9d86

Date:2015-07-28 14:35:45,827 
Message:Connection is alive ID:460f9930-263f-4bbd-ab0b-aad28bce9d86

Date:2015-07-28 14:36:15,812 
Message:Connection is dead ID:460f9930-263f-4bbd-ab0b-aad28bce9d86  

Date:2015-07-28 14:36:33,734 
Message:OnDisconnected called for an unclean disconnect for ID:2|200000

We have disconnected client immediately after first message at  14:18. However the “IsALive” property is true until 14:35. It took around 17 to 18 minutes to recognize that the connection is dead and to call OnDisconnected on unclean disconnection of client.

**Comment by halter73** [comment]
Do you have a sample app that you could send me that exhibits this behavior? Maybe you could put the sample on GitHub, and I could try it out.

Also, how are you disabling your client's internet? I've tried both disconnecting an Ethernet cable and turning off my laptop's WiFi. In both cases it took a little over 40 seconds for an unclean disconnect to fire.

Lastly, getting logs from SignalR itself could be helpful. [This guide](http://www.asp.net/signalr/overview/testing-and-debugging/enabling-signalr-tracing#server) explains how to enable SignalR's tracing.

**Comment by swl10** [comment]
I've also been involved in looking at this issue with @UshaV-Questionmark and @Joe-U-Questionmark 

It appears to me that, by design, SignalR servers don't know if the client is dead or not and they rely on notification from the underlying websocket for connection failures - i.e., the OnClose callback.  (The same is not true the other way around of course as the server can be configured to send keep-alive messages to the client periodically so that the client always knows if it is connected.)

Sadly, you can't just expect a write failure from a websocket as an indication of a broken connection (it may remain buffered somewhere).  Different network/proxy topologies are likely to behave differently.

Websockets don't automatically monitor the underlying connection status either.  IMO, the only reliable way is to issue ping requests from the server and check for pong responses from the client.  AFAICT SignalR is not doing ping/pong - those message types don't appear to have been exposed by the underlying websocket API.

As a result, the best solution I can suggest is to configure IIS websockets to do the ping/pong for you.  This ensures that your connection will close if it breaks unexpectedly.  I found the following SO answer useful in this respect:
http://stackoverflow.com/questions/19502755/websocket-clients-state-not-changing-on-network-loss  

Early testing suggests this has resolved our problem.

**Comment by halter73** [comment]
It's great to hear that it looks like you've resolved this problem by enabling WebSocket ping/pong in IIS. I did not know about this configuration setting previously. I made sure to upvote the answer on SO.

@Rick-Anderson Do you think we could add this to our [troubleshooting docs](http://www.asp.net/signalr/overview/testing-and-debugging/troubleshooting)?

Thanks for reporting back with the fix.

**Comment by Rick-Anderson** [comment]
@halter73 @swl10  good idea, I'll get that added.

**Comment by UshaV-Questionmark** [comment]
We are trying to determine the optimal value for "pingInterval". We found that it is somehow related to KeepAlive setting of SignalR. We are not getting ping requests if "pingInterval" value is more than KeepAlive value which by default 10 seconds. 

Could you please tell us what is the relationship between these two settings "pingInterval" and "KeepAlive"?

**Comment by halter73** [comment]
SignalR's "pingInterval" has no relation to WebSocket ping/pongs or "KeepAlive".

The pingInterval configures how how often SignalR sends an Ajax GET request (usually to /signalr/ping) so cookies get refreshed.

I go into more detail on SO: http://stackoverflow.com/a/25634573/719967

**Comment by swl10** [comment]
I think there is a misunderstanding here, the pingInterval here means the IIS websocket pingInterval.  On the wire we see an empty text frame '\x81\x02{}' received every 10s from the server which I assume is the websocket keep alive implemented at the SignalR level.  If we set IIS's pingInterval to 5s we receive ping frames '\x89\x04ping' from IIS but if we set it to, say, 15s we do not see any ping frames and the problem with the failure to detect broken sessions returns.  It looks like IIS is only sending ping frames when the connection has been idle for the pingInterval, we're wondering if anyone can confirm that.  If this is the case, then SignalR's keep alive frames are scuppering the detection of failed clients and we should recommend that SignalR's websocket keep-alive is always larger than the IIS websocket pingInterval if prompt handling of unclean client disconnect is important.  FYI, it appears that IIS will close the connection fairly quickly (within 10s) if it's ping frame is not responded to with a pong.

**Comment by Rick-Anderson** [comment]
@halter73 fixed at http://www.asp.net/signalr/overview/testing-and-debugging/troubleshooting#pong

**Comment by swl10** [comment]
That doc change is good as far as it goes but I think we need to address the issue with IIS not sending ping frames to be sure that this is a solution.  @halter73 do you know where can find out about the IIS websocket implementation?  The online docs do not go into enough detail and, in practice, the fix only works if you pick pingInterval carefully.

**Comment by aspnet-hello** [comment]
This issue has been closed as part of issue clean-up as described in https://blogs.msdn.microsoft.com/webdev/2018/09/17/the-future-of-asp-net-signalr/. If you're still encountering this problem, please feel free to re-open and comment to let us know! We're still interested in hearing from you, the backlog just got a little big and we had to do a bulk clean up to get back on top of things. Thanks for your continued feedback!

**Comment by Joe-U-Questionmark** [comment]
This issue is still occurring. It makes being able to track who is "online" using WebSockets near impossible... Please re-open.

**Comment by davidfowl** [comment]
@Joe-U-Questionmark configuring the IIS websocket ping pongs didn't work for you?

**Comment by anurse** [comment]
@Joe-U-Questionmark Can you provide a bit more detail on what you're still encountering and if the IIS configuration was able to resolve your issue (as @davidfowl asked)? I'd like to try and get the bottom of this but need to understand your scenario a little better to do so :).

> It looks like IIS is only sending ping frames when the connection has been idle for the pingInterval

This is the expected behavior. The ping frames are designed to "keep the connection alive" so are only sent if no other message was sent along the wire.

> If this is the case, then SignalR's keep alive frames are scuppering the detection of failed clients

As far as I know, this shouldn't be the case. The only detection we have in SignalR is the TCP connection timing out at the OS level due to unacknowledged writes, so even SignalR's ping frames should be able to produce that result.

**Comment by anurse** [comment]
Closing this as we haven't heard from you. Please feel free to comment if you're able to get the information we're looking for and we can reopen the issue to investigate further!
